### PR TITLE
Merge defaults with provided options

### PR DESCRIPTION
**Pull request by noelblaschke**
Use default options so it is not longer required to pass protocols with a custom options object.

### CODE REVIEW

**Comment by JSteunou** [comment]
Please do not change EOL ;)

**Comment by noelblaschke** [comment]
@JSteunou Updated

**Comment by noelblaschke** [comment]
#53 is not correct if you don't merge this change, too. Please also bump version <3

**Comment by JimiC** [comment]
@noelblaschke I can't see any benefit changing the code to your proposal. Can you elaborate the case where this is applicable?

**Comment by JSteunou** [comment]
#53 is still correct because the actual code make it still optional.

About the benefit of this PR:

:-1: 

1. This is API breaking, so will need a major release
2. WebSocket protocols are optional, this is just a default option to ease rapid development, but should certainly be set at you convenience 

:+1: 

1. I can imagine the frustration for some developers to lose the default protocols parameter when using options for the 1st time :(

**Comment by JimiC** [comment]
@JSteunou The alternative would be:

```
client: function(url, options = {}) {
        const ws = new WebSocket(url, options.protocols || VERSIONS.supportedProtocols());
        return new Client(ws, options);
    },
```

**Comment by JSteunou** [comment]
I guess this is *less* breaking. Just a little for those using `protocols` inside the Client object, but I don't think this happens. Good call @JimiC :+1:

**Comment by JSteunou** [comment]
@noelblaschke I fixed it through #57

**Pull request closed without merging**
