### PR TITLE
adding test suite

### PR DESCRIPTION
**Pull request by yeyu456**
Except the test files, adding some dev dependencies package for testing.
Using mocha, chai, karma with some plugins as test framework.
And using the gulp for tasks like creating a mock server and the code coverage.
Libraries like core-js, sockjs and sockjs-client are make sure the browser compatibility test pass.

### CODE REVIEW

**Comment by JSteunou** [comment]
Wonderful ! Until I review it, could you format your code to respect the actual format ? Mostly indent (4 spaces) and end of file.

**Comment by yeyu456** [comment]
Ok, no problem.Sorry for the format.Maybe the ide setting problem.

**Comment by yeyu456** [comment]
@JSteunou As for the format, should we need to switch jscs to eslint since they're merged?

**Comment by JSteunou** [comment]
Yep, I would like to to replace jshint + jscs by eslint

**Comment by yeyu456** [comment]
I can do that by the way if you don't mind.

**Comment by JSteunou** [comment]
Would be great! On another PR though.

**Comment by yeyu456** [comment]
Barely use github for me, I think i have make a big mistake using the master repo for PR.Now i cannot do other PR since every new branch will add all of these commits. @JSteunou I will close this PR and redo it with a new fork and branch.

**Comment by JSteunou** [comment]
Ok. Did not see you where PRing from master. Best practice is too create a branch on your fork and PR from that branch so you can do multiple PR without being polluted.

**Pull request closed without merging**
