### PR TITLE
Use 2 fallbacks for ws protocol #74 #75

### PR DESCRIPTION
**Pull request by JSteunou**
Add several fallbacks on protocol

1. if there are no `ws.protocol` (being server or ws client fault) I will fallback on `Client options.protocols` 1st item
2. event with this, if there is still a no match in supported version, I kept the 2nd fallback, but change it from a list of all STOMP versions to only the newest. If you know you have issues with your server or your ws client, and need STOMP 1.0 instead of 1.2, force the protocol with `options.protocols`

And for a better logging remove usage `console.warn` to use the internal `debug` function instead which does not log if `options.debug` is falsy.

### CODE REVIEW

**Review by Marcsimm — APPROVED** [review]

**Comment by Marcsimm** [comment]
When can a new release of this be made?

**Comment by JSteunou** [comment]
I'm waiting for @Polve and @krusche feedbacks

**Comment by Polve** [comment]
Is the release 1.2.5 pushed on the npm repository already?

**Comment by krusche** [comment]
Would be great if you could publish it as beta, then I can test if it works

**Comment by JSteunou** [comment]
@Polve nope I was waiting for your reviews / tests

Guys, help me helping you, npm can pull git repo and branches :) This branch contains dist folder and up to date build files.

**Comment by Polve** [comment]
The branch is not working for me, I wrote the details here (sorry, I know, wrong thread)

https://github.com/JSteunou/webstomp-client/issues/75

**Comment by JSteunou** [comment]
published in 1.2.5

**Pull request closed without merging**
