### PR TITLE
Add types definitions.

### PR DESCRIPTION
**Pull request by JimiC**
Resolves issue #7.

### CODE REVIEW

**Comment by JimiC** [comment]
**How to keep types up to date when changing the code.**

Just reflect in the `index.d.ts` file, the changes you make, to the signatures of the functions, or their properties, that you are exporting.

**Comment by JSteunou** [comment]
I'm really not into TS, would you be volunteer to keep an eye on this file if I do some changes in the future?

**Comment by JimiC** [comment]
No promises, but as long as I'm active in the community, why not. 😄

**Comment by JSteunou** [comment]
Thank you @JimiC !

**Pull request merged**
