### PR TITLE
Export Frame helper class

### PR DESCRIPTION
**Pull request by ms88privat**
Thanks for this great library!

We are using it with the stomp protocol. It expects to receive a special 'CONNECTED' frame which I try to send with the mockServer. It would be great to be able to use the already existing frame class for this.

### CODE REVIEW

**Review by JSteunou — CHANGES_REQUESTED** [review]
Seems ok to me. Could you remove the spaces inside the brackets?

**Comment by ms88privat** [comment]
Done, thanks 👍

**Comment by ms88privat** [comment]
@JSteunou haha, I just realised what I did here. My mind was by the other package:
https://github.com/thoov/mock-socket. There you can send messages via a mockServer. 
But of course, the change has to be done here, so everything is correct in the end, but I think it did sound strange to you 🤣

**Comment by ms88privat** [comment]
@JSteunou Could you please publish 1.2.1 :)? Thank you very much

**Pull request merged**
